app_id: "e8aacb5a-8947-47a9-97f2-b4eb60a67ca2"
app_secret: "n6J.LmABFwI7~GJv5L8xD.QU0F~9OulemN"
redirect: "http://localhost:8000/printing_portal/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
