# Generated by Django 3.0.4 on 2021-06-12 20:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_roll_number', models.IntegerField(default=0)),
                ('customer_email', models.EmailField(default='customer@iitg.ac.in', max_length=254)),
                ('shopkeeper_email', models.EmailField(default='shopkeeper@iitg.ac.in', max_length=254)),
                ('shopkeeper_location', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('cost', models.IntegerField(default=0)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.BooleanField(default=False)),
                ('printing_status', models.BooleanField(default=False)),
            ],
        ),
    ]
