# Generated by Django 3.0.4 on 2021-06-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_roll_number',
        ),
    ]
