# Generated by Django 3.0.4 on 2021-06-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_customer_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='order',
            name='black_and_white',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='docfile',
            field=models.FileField(default='blank.pdf', upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='ending_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='no_of_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='starting_page',
            field=models.IntegerField(default=1),
        ),
    ]
