# Generated by Django 3.0.4 on 2021-06-19 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ending_page',
        ),
        migrations.RemoveField(
            model_name='order',
            name='starting_page',
        ),
        migrations.AddField(
            model_name='order',
            name='OTP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='collected_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='black_and_white',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='docfile',
            field=models.FileField(default='blank.pdf', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=50),
        ),
    ]
