# Generated by Django 3.0.4 on 2021-06-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210619_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='order_id',
        ),
    ]
