# Generated by Django 3.0.4 on 2021-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210619_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='docfile',
            field=models.FileField(default='blank.pdf', upload_to=''),
        ),
    ]
